default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: guestbook_dev

test:
  <<: *default
  database: guestbook_test

production:
  <<: *default
  database: guestbook_prod